#+title: Encryption
#+author: Gábor Udvari

* Encryption mishaps
:PROPERTIES:
:VISIBILITY: fold
:END:

Encryption is difficult, here are some real world mishaps to get you feel better about your struggles:

- The infamous Debian OpenSSL bug from 2008. While packaging OpenSSL Debian package maintainers introduced a patch that made the random key generator predictable. It was not fixed for 2 years:

  https://lists.debian.org/debian-security-announce/2008/msg00152.html

- Kali Linux lost their repository signing key in 2025, and had to ask the community to manually download a new one:

  https://www.kali.org/blog/new-kali-archive-signing-key/

* AGE

** General info

Official homepage:

- https://github.com/FiloSottile/age

Arguments against using GPG:

- https://blog.cryptographyengineering.com/2014/08/13/whats-matter-with-pgp/
- https://www.latacora.com/blog/2019/07/16/the-pgp-problem/
- https://soatok.blog/2024/11/15/what-to-use-instead-of-pgp/

Arguments against using Age:

- The Go implementation does not have pinentry support yet, a password plugin is planned since 2022:
  https://github.com/FiloSottile/age/discussions/256#discussioncomment-2638232
  The Rust implementation rage does have pinentry support, but that is not yet packaged in Guix.

** Usage

Generating an age identity file with a password, and outputting into a text file written in the PEM format:

#+begin_src shell
  age-keygen | age -p -a > key.age
#+end_src

The above identity file can be used as is, age will discover that it is password protected, and it will decrypt it before use.

Getting the file recipient part of a password protected age identity file:

#+begin_src shell
  age -d key.age | age-keygen -y
#+end_src

The above will be the recipient, or the the public part.

** Guix Home config

#+begin_src scheme :noweb-ref guix-home
  (use-modules (gnu packages golang-crypto))

  (define %home-packages
    (append %home-packages
            (list age
                  age-keygen)))
#+end_src

* Passage

** Usage

To configure passage with a password protected identity file follow these steps:
1. Generate a password protected identity file in a PEM format:
   #+begin_src shell
     age-keygen | age -p -a > key.age
   #+end_src
2. Append that file to the passage identities:
   #+begin_src shell
     cat key.age >> ~/.passage/identities
   #+end_src
3. Append the recipient part of that file to the passage recipients:
   #+begin_src shell
     age -d key.age >> ~/.passage/store/.age-recipients
   #+end_src
4. Now the setup is ready, you can remove or backup the original ~key.age~ file.

** Guix Home config

#+begin_src scheme :noweb-ref guix-home
  (use-modules (gnu packages password-utils))

  (define %home-packages
    (append %home-packages
            (list pass-age)))
#+end_src

* GPG

** General info

*** Guides on using GPG

- https://wiki.debian.org/Subkeys
- https://security.stackexchange.com/questions/31594/what-is-a-good-general-purpose-gnupg-key-setup/31598#31598
- https://gpg.wtf/
- https://www.iduoad.com/posts/gpg-for-everything/

*** Articles about GPG

- https://www.propublica.org/article/the-worlds-email-encryption-software-relies-on-one-guy-who-is-going-broke

** Usage

*** To generate a new key

#+begin_src bash
  gpg --full-generate-key
#+end_src

*** To list out all the keys

Note, you can add ~--with-keygrip~ to list out the keygrips as well, but my GPG configuration already has that.

#+begin_src bash
  gpg --list-keys
#+end_src

*** To export the private key for backup

#+begin_src bash
  gpg --export-secret-key --armor --export-options export-backup >gpg_private.asc
#+end_src

*** To import the private key from the backup

#+begin_src bash
  gpg --import gpg_private.asc
#+end_src

After the import you need to trust the imported key:

#+begin_src bash
  gpg --edit-key <<KEY_ID>> trust quit
#+end_src

*** To encrypt a file

#+begin_src bash
  gpg --encrypt --output ~/.authinfo.gpg --recipient <USER> ~/.authinfo
#+end_src

** Configuration

Put the GPG config file into an XDG compliant folder. For this to work, the ~GNUPGHOME~ environment variable is configured in the ~.profile~ file.

#+begin_src text :noweb yes :exports none :mkdirp yes :tangle home/.local/share/gnupg/gpg.conf
  <<gpg-config>>
#+end_src

#+begin_src text :noweb-ref gpg-config
  # Get rid of the copyright notice
  no-greeting
  # Do not print a version number or a comment
  no-emit-version
  no-comments

  # Use UTF-8
  charset utf-8

  # Display long key IDs
  keyid-format 0xlong

  # List all keys (or the specified ones) along with their fingerprints
  with-fingerprint
  with-keygrip
#+end_src

** Guix home services

We need to start the GPG Agent service and also set the pinentry program to ~/bin/pinentry~.

We also need to link the ~gpg.conf~ file to its final folder.

#+BEGIN_SRC scheme :noweb-ref guix-home
  (use-modules (gnu home services gnupg))

  (define %home-services
    (append %home-services
            (list
             (service home-gpg-agent-service-type
                      (home-gpg-agent-configuration
                       (pinentry-program
                        (file-append pinentry "/bin/pinentry"))
                       (ssh-support? #f)))

             (simple-service 'gpg-symlinking-service
                             home-files-service-type
                             `((".local/share/gnupg/gpg.conf"
                                ,(local-file "home/.local/share/gnupg/gpg.conf" "gpg-conf")))))))
#+END_SRC

** Guix packages

#+BEGIN_SRC scheme :noweb-ref guix-home
  (use-modules (gnu packages gnupg))

  (define %home-packages
    (append %home-packages
            (list gnupg
                  pinentry)))
#+END_SRC

* SOPS

SOPS is a tool to encrypt contents of a file, eg. values in a JSON or YAML file.

https://getsops.io/

** Usage

*** Using password encrpyted age file for description

You can use the ~SOPS_AGE_KEY~ environment variable to decrypt an age key before decryption, eg.:

#+begin_src bash
  SOPS_AGE_KEY="$(age -d ~/.local/share/age/key.age)" sops -d secret.yaml
#+end_src
